# Copyright 2023 Embyr
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "ryst"
version = "0.1.0"
edition = "2021"

authors = ["Embyr"]
license = "Apache-2.0"
description = """\
    The ryst CLI tool.
"""
repository = "https://github.com/embyrai/ryst"

[dependencies]
ryst-openai = { path = "../openai", version = "=0.1.0" } # ryst-openai Version

[features]
default = []

stable = [
    "default",
]

experimental = [
  # The experimental feature extends stable:
  "stable",
  # The following features are experimental:
]

[package.metadata.docs.rs]
features = [
  "stable",
  "experimental"
]
